[versions]
kotlin = "1.9.10"
appCompat = "1.6.1"
androidx_core = "1.12.0"
constraint_layout = "2.1.4"
junit = "4.13.2"
androidx_testRunner = "1.5.2"
espresso = "3.5.1"
recyclerView = "1.3.2"
cardView = "1.0.0"
glide = "4.11.0"
material = "1.10.0"
swipeRefreshLayout = "1.1.0"

# shared versions
buildTools = "34.0.0"
versionCodeInt = "1"
versionNameString = "1.0.0"
jdkVersion = "1.8"
minSdkVersion = "21"
compileSdkVersion = "34"


[libraries]
kotlin_jdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
app_compat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint_layout" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx_testRunner = { module = "androidx.test:runner", version.ref = "androidx_testRunner" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide_annotationProcessor = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
material = { module = "com.google.android.material:material", version.ref = "material" }
swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }

[bundles]
unitTesting = ["junit"]
androidUi = ["app_compat", "androidx_core", "constraint_layout", "recyclerView", "cardView", "swipeRefreshLayout"]
androidAutomation = ["androidx_testRunner","espresso"]